server:
  port:  9100
spring:
    application:
        name: fis-gateway
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:9000/eureka/    
                
zuul:
  routes:
    fis-app-one:                 # 选课中心服务
      path: /application/**            # 访问前缀
      serviceId: xiaolu-computer     # 服务名
      stripPrefix: false        # 移除前缀，默认为true
      
    fis-consume-one:                 # 选课中心服务
      path: /consumer/**            # 访问前缀
      serviceId: xiaolu-consumer-one     # 服务名
      stripPrefix: false        # 移除前缀，默认为true  